### ISSUE TITLE
java.lang.NullPointerException when trying to notified

### ISSUE THREAD

**Issue by TMadMac** [tomzo/gocd-rocketchat-plugin#2]
Platform:
* goCD version 19.2
* plugin : last available 0.1.1
* plugin is configured (rocketchat API server, login, password, room)

When a failed stage append, goCD server's log have those logs :
```
2019-06-24 08:14:14,131 WARN  [qtp712256162-19] TemplateConfigService:192 - Error notifying plugin - cd.go.plugin.notification.rocketchat with settings change
java.lang.RuntimeException: Interaction with plugin with id 'cd.go.plugin.notification.rocketchat' implementing 'notification' extension failed while requesting for 'go.plugin-settings.plugin-settings-changed'. Reason: [j
ava.lang.NullPointerException]
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:57)
        at com.thoughtworks.go.plugin.access.common.AbstractExtension.notifyPluginSettingsChange(AbstractExtension.java:83)
        at com.thoughtworks.go.server.service.PluginService.notifyPluginSettingsChange(PluginService.java:190)
        at com.thoughtworks.go.server.service.PluginService.updatePluginSettingsAndNotifyPluginSettingsChangeListeners(PluginService.java:166)
        at com.thoughtworks.go.server.service.PluginService.updatePluginSettings(PluginService.java:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:425)
...
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:292)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:228)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:145)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        ... 534 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at cd.go.plugin.notification.rocketchat.RocketChatPlugin.handle(RocketChatPlugin.java:85)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:148)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:286)
        ... 537 common frames omitted
Caused by: java.lang.NullPointerException: null
        at cd.go.plugin.notification.rocketchat.RocketChatPlugin.handle(RocketChatPlugin.java:65)
        ... 539 common frames omitted
```

**Comment by tomzo** [comment]
I was running the plugin 0.1.1 with 19.3.0 until recently, and there was no such error. 
Stacktrace suggests that `request.requestName()` is null, so perhaps server sent something unexpected.

**Comment by TMadMac** [comment]
Note that the notification is send to RocketChat (it works) but there is still those long debug logs after each notification is send.

I tried to look into the trigger of the plugin to find out what could be missing. But I am not aware enough of the goCD API / plugin API to find something relevant.
I will first upgrade to last version of goCD and look at the log to see if anything as changed.
